name: Javascript Runner

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select person
        options:
          - 'aiswarya_anil'
          - 'aiswarya_mohan'
          - 'aleena'
          - 'arathy'
          - 'aswin'
          - 'athira'
          - 'dinu'
          - 'honey'
          - 'krishna'
          - 'mithun'
          - 'nikhil'
          - 'sidharth'
          - 'solomon'
      file_path:
        description: Input the file relative path
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    name: Javascript Run ${{ github.event.inputs.choice }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run script - specific path
        if: ${{ github.event.inputs.choice }}
        run: node ${{ github.event.inputs.file_path }}

      - name: Run script - full folder
        if: ${{ github.event.inputs.choice }}
        run: |
          cd ${{ github.event.inputs.choice }}
          for file in *.js; do
            node "$file"
          done
